using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace BrodheimDataAccess.Migrations
{
    /// <inheritdoc />
    public partial class AddOportunidadesTableToDb : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Oportunidades",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    NomeTrabalho = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    NomeEmpresa = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ImageEmpresa = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Localizacao = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    NomeFuncao = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DetalhesFuncao = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TipoContrato = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DateTrabalho = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Oportunidades", x => x.ID);
                });

            migrationBuilder.InsertData(
                table: "Oportunidades",
                columns: new[] { "ID", "DateTrabalho", "DetalhesFuncao", "ImageEmpresa", "Localizacao", "NomeEmpresa", "NomeFuncao", "NomeTrabalho", "TipoContrato" },
                values: new object[,]
                {
                    { 1, new DateTime(2023, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Com mais de 75 anos de história e crescimento, o Grupo Brodheim é hoje a mais importante empresa de moda e ótica em Portugal. Com a visão de ser a referência na gestão de retalho premium no mundo da moda e da ótica, é considerada uma das Melhores Empresas Para Trabalhar em Portugal, e o lugar onde tu queres estar! A missão de proporcionar a todos os nossos clientes e stakeholders, um serviço de excelência e uma experiência comercial e relacional única, é sentida e vivida todos os dias pelos nossos colaboradores que incorporam os nossos valores: ambição, sustentabilidade, credibilidade, empowerment e atitude.\r\n\r\nVeste a camisola VANS, na nossa loja no MadeiraShopping, em regime Full-Time 40h (rotativo).\r\n\r\nA TUA MISSÃO:\r\n– Garantir uma experiência comercial de excelência\r\n– Garantir vendas\r\n– Assegurar as tarefas diárias da loja\r\n– Reportar diretamente ao Store Manager\r\n\r\nQUE PERFIL PROCURAMOS?\r\nO candidato ideal terá o seguinte perfil:\r\n– Experiência no retalho, em marcas do mesmo segmento (preferencial)\r\n– Gosto por proporcionar uma experiência comercial excecional\r\n– Ótimas competências comunicacionais\r\n– Elevado perfil comercial\r\n– Foco no cumprimento de objetivos\r\n– Conhecimentos de inglês em contexto de vendas\r\n– Disponibilidade para realizar horários rotativos e flexíveis\r\n– Carta de condução, viatura própria (requisito preferencial para deslocação para o shopping)\r\n\r\nO QUE TE OFERECEMOS:\r\n– Um ambiente de trabalho envolvente\r\n– Possibilidade de crescimento e progressão na carreira\r\n– Oportunidade de Formação especializada contínua\r\n– Incentivos mensais\r\n– Participação em ações de solidariedade social e ambiental\r\n– Protocolos e parcerias exclusivas para colaboradores do Grupo Brodheim\r\n\r\nSe reúnes os requisitos, esta vaga é para ti!", "", "Funchal", "Vans", "Sales Assistant", "Sales Assistant (M/F) – Vans Funchal | FT", "Full Time" },
                    { 2, new DateTime(2023, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Com mais de 75 anos de história e crescimento, o Grupo Brodheim é hoje a mais importante empresa de moda e ótica em Portugal. Com a visão de ser a referência na gestão de retalho premium no mundo da moda e da ótica, é considerada uma das Melhores Empresas Para Trabalhar em Portugal, e o lugar onde tu queres estar! A missão de proporcionar a todos os nossos clientes e stakeholders, um serviço de excelência e uma experiência comercial e relacional única, é sentida e vivida todos os dias pelos nossos colaboradores que incorporam os nossos valores: ambição, sustentabilidade, credibilidade, empowerment e atitude.\r\n\r\nVeste a camisola VANS, na nossa loja no MadeiraShopping, em regime Full-Time 40h (rotativo).\r\n\r\nA TUA MISSÃO:\r\n– Garantir uma experiência comercial de excelência\r\n– Garantir vendas\r\n– Assegurar as tarefas diárias da loja\r\n– Reportar diretamente ao Store Manager\r\n\r\nQUE PERFIL PROCURAMOS?\r\nO candidato ideal terá o seguinte perfil:\r\n– Experiência no retalho, em marcas do mesmo segmento (preferencial)\r\n– Gosto por proporcionar uma experiência comercial excecional\r\n– Ótimas competências comunicacionais\r\n– Elevado perfil comercial\r\n– Foco no cumprimento de objetivos\r\n– Conhecimentos de inglês em contexto de vendas\r\n– Disponibilidade para realizar horários rotativos e flexíveis\r\n– Carta de condução, viatura própria (requisito preferencial para deslocação para o shopping)\r\n\r\nO QUE TE OFERECEMOS:\r\n– Um ambiente de trabalho envolvente\r\n– Possibilidade de crescimento e progressão na carreira\r\n– Oportunidade de Formação especializada contínua\r\n– Incentivos mensais\r\n– Participação em ações de solidariedade social e ambiental\r\n– Protocolos e parcerias exclusivas para colaboradores do Grupo Brodheim\r\n\r\nSe reúnes os requisitos, esta vaga é para ti!", "", "Lisboa", "Timberland", "Sales Assistant", "Sales Assistant (M/F) – Timberland Amoreiras | PT", "Part Time" },
                    { 3, new DateTime(2023, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), "Com mais de 75 anos de história e crescimento, o Grupo Brodheim é hoje a mais importante empresa de moda e ótica em Portugal. Com a visão de ser a referência na gestão de retalho premium no mundo da moda e da ótica, é considerada uma das Melhores Empresas Para Trabalhar em Portugal, e o lugar onde tu queres estar! A missão de proporcionar a todos os nossos clientes e stakeholders, um serviço de excelência e uma experiência comercial e relacional única, é sentida e vivida todos os dias pelos nossos colaboradores que incorporam os nossos valores: ambição, sustentabilidade, credibilidade, empowerment e atitude.\r\n\r\nVeste a camisola VANS, na nossa loja no MadeiraShopping, em regime Full-Time 40h (rotativo).\r\n\r\nA TUA MISSÃO:\r\n– Garantir uma experiência comercial de excelência\r\n– Garantir vendas\r\n– Assegurar as tarefas diárias da loja\r\n– Reportar diretamente ao Store Manager\r\n\r\nQUE PERFIL PROCURAMOS?\r\nO candidato ideal terá o seguinte perfil:\r\n– Experiência no retalho, em marcas do mesmo segmento (preferencial)\r\n– Gosto por proporcionar uma experiência comercial excecional\r\n– Ótimas competências comunicacionais\r\n– Elevado perfil comercial\r\n– Foco no cumprimento de objetivos\r\n– Conhecimentos de inglês em contexto de vendas\r\n– Disponibilidade para realizar horários rotativos e flexíveis\r\n– Carta de condução, viatura própria (requisito preferencial para deslocação para o shopping)\r\n\r\nO QUE TE OFERECEMOS:\r\n– Um ambiente de trabalho envolvente\r\n– Possibilidade de crescimento e progressão na carreira\r\n– Oportunidade de Formação especializada contínua\r\n– Incentivos mensais\r\n– Participação em ações de solidariedade social e ambiental\r\n– Protocolos e parcerias exclusivas para colaboradores do Grupo Brodheim\r\n\r\nSe reúnes os requisitos, esta vaga é para ti!", "", "Lisboa", "Emporio Armani", "Sales Assistant", "Sales Assistant (M/F) – Emporio Armani (Full-Time)", "Full Time" },
                    { 4, new DateTime(2023, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), "Com mais de 75 anos de história e crescimento, o Grupo Brodheim é hoje a mais importante empresa de moda e ótica em Portugal. Com a visão de ser a referência na gestão de retalho premium no mundo da moda e da ótica, é considerada uma das Melhores Empresas Para Trabalhar em Portugal, e o lugar onde tu queres estar! A missão de proporcionar a todos os nossos clientes e stakeholders, um serviço de excelência e uma experiência comercial e relacional única, é sentida e vivida todos os dias pelos nossos colaboradores que incorporam os nossos valores: ambição, sustentabilidade, credibilidade, empowerment e atitude.\r\n\r\nVeste a camisola VANS, na nossa loja no MadeiraShopping, em regime Full-Time 40h (rotativo).\r\n\r\nA TUA MISSÃO:\r\n– Garantir uma experiência comercial de excelência\r\n– Garantir vendas\r\n– Assegurar as tarefas diárias da loja\r\n– Reportar diretamente ao Store Manager\r\n\r\nQUE PERFIL PROCURAMOS?\r\nO candidato ideal terá o seguinte perfil:\r\n– Experiência no retalho, em marcas do mesmo segmento (preferencial)\r\n– Gosto por proporcionar uma experiência comercial excecional\r\n– Ótimas competências comunicacionais\r\n– Elevado perfil comercial\r\n– Foco no cumprimento de objetivos\r\n– Conhecimentos de inglês em contexto de vendas\r\n– Disponibilidade para realizar horários rotativos e flexíveis\r\n– Carta de condução, viatura própria (requisito preferencial para deslocação para o shopping)\r\n\r\nO QUE TE OFERECEMOS:\r\n– Um ambiente de trabalho envolvente\r\n– Possibilidade de crescimento e progressão na carreira\r\n– Oportunidade de Formação especializada contínua\r\n– Incentivos mensais\r\n– Participação em ações de solidariedade social e ambiental\r\n– Protocolos e parcerias exclusivas para colaboradores do Grupo Brodheim\r\n\r\nSe reúnes os requisitos, esta vaga é para ti!", "", "Vila do Conde - Porto", "Timberland", "Sales Assistant", "Sales Assistant (M/F) – Timberland Outlet Vila do Conde | FT", "Full Time" },
                    { 5, new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), "Com mais de 75 anos de história e crescimento, o Grupo Brodheim é hoje a mais importante empresa de moda e ótica em Portugal. Com a visão de ser a referência na gestão de retalho premium no mundo da moda e da ótica, é considerada uma das Melhores Empresas Para Trabalhar em Portugal, e o lugar onde tu queres estar! A missão de proporcionar a todos os nossos clientes e stakeholders, um serviço de excelência e uma experiência comercial e relacional única, é sentida e vivida todos os dias pelos nossos colaboradores que incorporam os nossos valores: ambição, sustentabilidade, credibilidade, empowerment e atitude.\r\n\r\nVeste a camisola VANS, na nossa loja no MadeiraShopping, em regime Full-Time 40h (rotativo).\r\n\r\nA TUA MISSÃO:\r\n– Garantir uma experiência comercial de excelência\r\n– Garantir vendas\r\n– Assegurar as tarefas diárias da loja\r\n– Reportar diretamente ao Store Manager\r\n\r\nQUE PERFIL PROCURAMOS?\r\nO candidato ideal terá o seguinte perfil:\r\n– Experiência no retalho, em marcas do mesmo segmento (preferencial)\r\n– Gosto por proporcionar uma experiência comercial excecional\r\n– Ótimas competências comunicacionais\r\n– Elevado perfil comercial\r\n– Foco no cumprimento de objetivos\r\n– Conhecimentos de inglês em contexto de vendas\r\n– Disponibilidade para realizar horários rotativos e flexíveis\r\n– Carta de condução, viatura própria (requisito preferencial para deslocação para o shopping)\r\n\r\nO QUE TE OFERECEMOS:\r\n– Um ambiente de trabalho envolvente\r\n– Possibilidade de crescimento e progressão na carreira\r\n– Oportunidade de Formação especializada contínua\r\n– Incentivos mensais\r\n– Participação em ações de solidariedade social e ambiental\r\n– Protocolos e parcerias exclusivas para colaboradores do Grupo Brodheim\r\n\r\nSe reúnes os requisitos, esta vaga é para ti!", "", "Loulé - Faro", "Guess", "Warehouse Assistant", "Warehouse Assistant (M/F) – Guess Outlet Loulé | FT", "Full Time" },
                    { 6, new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), "Com mais de 75 anos de história e crescimento, o Grupo Brodheim é hoje a mais importante empresa de moda e ótica em Portugal. Com a visão de ser a referência na gestão de retalho premium no mundo da moda e da ótica, é considerada uma das Melhores Empresas Para Trabalhar em Portugal, e o lugar onde tu queres estar! A missão de proporcionar a todos os nossos clientes e stakeholders, um serviço de excelência e uma experiência comercial e relacional única, é sentida e vivida todos os dias pelos nossos colaboradores que incorporam os nossos valores: ambição, sustentabilidade, credibilidade, empowerment e atitude.\r\n\r\nVeste a camisola VANS, na nossa loja no MadeiraShopping, em regime Full-Time 40h (rotativo).\r\n\r\nA TUA MISSÃO:\r\n– Garantir uma experiência comercial de excelência\r\n– Garantir vendas\r\n– Assegurar as tarefas diárias da loja\r\n– Reportar diretamente ao Store Manager\r\n\r\nQUE PERFIL PROCURAMOS?\r\nO candidato ideal terá o seguinte perfil:\r\n– Experiência no retalho, em marcas do mesmo segmento (preferencial)\r\n– Gosto por proporcionar uma experiência comercial excecional\r\n– Ótimas competências comunicacionais\r\n– Elevado perfil comercial\r\n– Foco no cumprimento de objetivos\r\n– Conhecimentos de inglês em contexto de vendas\r\n– Disponibilidade para realizar horários rotativos e flexíveis\r\n– Carta de condução, viatura própria (requisito preferencial para deslocação para o shopping)\r\n\r\nO QUE TE OFERECEMOS:\r\n– Um ambiente de trabalho envolvente\r\n– Possibilidade de crescimento e progressão na carreira\r\n– Oportunidade de Formação especializada contínua\r\n– Incentivos mensais\r\n– Participação em ações de solidariedade social e ambiental\r\n– Protocolos e parcerias exclusivas para colaboradores do Grupo Brodheim\r\n\r\nSe reúnes os requisitos, esta vaga é para ti!", "", "Lisboa", "Michael Kors", "Sales Assistant", "Sales Assistant (M/F) – Michael Kors Aeroporto de Lisboa | FT", "Full Time" },
                    { 7, new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), "Com mais de 75 anos de história e crescimento, o Grupo Brodheim é hoje a mais importante empresa de moda e ótica em Portugal. Com a visão de ser a referência na gestão de retalho premium no mundo da moda e da ótica, é considerada uma das Melhores Empresas Para Trabalhar em Portugal, e o lugar onde tu queres estar! A missão de proporcionar a todos os nossos clientes e stakeholders, um serviço de excelência e uma experiência comercial e relacional única, é sentida e vivida todos os dias pelos nossos colaboradores que incorporam os nossos valores: ambição, sustentabilidade, credibilidade, empowerment e atitude.\r\n\r\nVeste a camisola VANS, na nossa loja no MadeiraShopping, em regime Full-Time 40h (rotativo).\r\n\r\nA TUA MISSÃO:\r\n– Garantir uma experiência comercial de excelência\r\n– Garantir vendas\r\n– Assegurar as tarefas diárias da loja\r\n– Reportar diretamente ao Store Manager\r\n\r\nQUE PERFIL PROCURAMOS?\r\nO candidato ideal terá o seguinte perfil:\r\n– Experiência no retalho, em marcas do mesmo segmento (preferencial)\r\n– Gosto por proporcionar uma experiência comercial excecional\r\n– Ótimas competências comunicacionais\r\n– Elevado perfil comercial\r\n– Foco no cumprimento de objetivos\r\n– Conhecimentos de inglês em contexto de vendas\r\n– Disponibilidade para realizar horários rotativos e flexíveis\r\n– Carta de condução, viatura própria (requisito preferencial para deslocação para o shopping)\r\n\r\nO QUE TE OFERECEMOS:\r\n– Um ambiente de trabalho envolvente\r\n– Possibilidade de crescimento e progressão na carreira\r\n– Oportunidade de Formação especializada contínua\r\n– Incentivos mensais\r\n– Participação em ações de solidariedade social e ambiental\r\n– Protocolos e parcerias exclusivas para colaboradores do Grupo Brodheim\r\n\r\nSe reúnes os requisitos, esta vaga é para ti!", "", "Lisboa", "Brodheim", "Trade Marketing", "Trade Marketing (M/F) – Substituição de Licença de Maternidade", "Full Time" }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Oportunidades");
        }
    }
}
