// <auto-generated />
using System;
using Brodheim;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrodheimDataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Brodheim.Models.Brands", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ImageBrand")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Brands", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ImageBrand = ""
                        },
                        new
                        {
                            ID = 2,
                            ImageBrand = ""
                        },
                        new
                        {
                            ID = 3,
                            ImageBrand = ""
                        },
                        new
                        {
                            ID = 4,
                            ImageBrand = ""
                        },
                        new
                        {
                            ID = 5,
                            ImageBrand = ""
                        },
                        new
                        {
                            ID = 6,
                            ImageBrand = ""
                        },
                        new
                        {
                            ID = 7,
                            ImageBrand = ""
                        },
                        new
                        {
                            ID = 8,
                            ImageBrand = ""
                        },
                        new
                        {
                            ID = 9,
                            ImageBrand = ""
                        },
                        new
                        {
                            ID = 10,
                            ImageBrand = ""
                        },
                        new
                        {
                            ID = 11,
                            ImageBrand = ""
                        },
                        new
                        {
                            ID = 12,
                            ImageBrand = ""
                        },
                        new
                        {
                            ID = 13,
                            ImageBrand = ""
                        },
                        new
                        {
                            ID = 14,
                            ImageBrand = ""
                        });
                });

            modelBuilder.Entity("Brodheim.Models.HomePageSlider", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ImageSlider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SliderTop", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ImageSlider = "",
                            SubTitle = "Mais de 70 anos de experiência a representar marcas premium e de luxo na Moda e na Ótica",
                            Title = "Grupo Brodheim"
                        },
                        new
                        {
                            ID = 2,
                            ImageSlider = "",
                            SubTitle = "O nosso crescimento é assente em 5 valores: Credibilidade, Sustentabilidade, Ambição, Empowerment e Atitude.",
                            Title = "Carreiras Brodheim"
                        },
                        new
                        {
                            ID = 3,
                            ImageSlider = "",
                            SubTitle = "Na Brodheim, somos apaixonados pelo que fazemos!",
                            Title = "Trabalhar na Brodheim"
                        });
                });

            modelBuilder.Entity("Brodheim.Models.HomePageSlidersTestemunhas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamePerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SliderTestemunhas", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "É um privilégio poder contribuir diariamente e partilhar a vontade de acresentar valor ao negócio, numa cultura aberta, onde o erro faz parte do crescimento, o sentimento de pertença é grande, e o reconhecimento e as celebrações são enormes!",
                            NamePerson = "Alexandra",
                            PersonImage = "",
                            PersonPosition = "Visual Merchandising"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Pertencer ao Grupo Brodheim é um desafio permanente, onde o fator humano está sempre presente. Aqui, desenvolvi a minha carreira. Comecei a trabalhar na Sede nos Recursos Humanos, e, entretanto, surgiu a oportunidade de ser Back Office Coordinator onde dou apoio a uma das principais lojas do Grupo.",
                            NamePerson = "André",
                            PersonImage = "",
                            PersonPosition = "Store Manager"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Todas as vitórias e obstáculos foram importantes para me tornar o profissional que sou hoje. As conquistas de que mais me orgulho são: os colegas que ajudei a desenvolver, as formações que pude dar e os prémios coletivos e individuais que tenho conquistado.",
                            NamePerson = "Bruno",
                            PersonImage = "",
                            PersonPosition = "Store Manager"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Trabalhar no Grupo Brodheim é fazer parte de uma estrutura que privilegia o trabalho em equipa, significa ter certeza de estar dentro de um projeto vencedor com grandes líderes, pessoas inspiradoras que incentivam a progredir. A Brodheim abriu-me as portas do mercado profissional para a minha área de formação.",
                            NamePerson = "Igor",
                            PersonImage = "",
                            PersonPosition = " Treasury & Credit Control"
                        },
                        new
                        {
                            ID = 5,
                            Description = "“Desafio” resume o que é trabalhar na Brodheim. Somos constantemente desafiados: a pensar “fora da caixa”, a ter autonomia, a ter novas missões, a aprender pela experiência sem receio de errar, a fazer aquilo que nos apaixona dentro e fora da empresa e a viver os valores da mesma.",
                            NamePerson = "Lídia",
                            PersonImage = "",
                            PersonPosition = " Head of Customer & Digital Marketing"
                        },
                        new
                        {
                            ID = 6,
                            Description = "Trabalhar no grupo Brodheim é um orgulho e uma satisfação enorme. A grandiosidade da empresa, a sua tradição, o reconhecimento e respeito que parceiros e clientes têm por nós, desde os seus valores, princípios, responsabilidades sociais e ecológicas. O grupo dá-me a oportunidade de crescer em várias valências e competências, é um lugar que valoriza os profissionais, dando oportunidades para todos mostrarem o seu potencial.",
                            NamePerson = "Jorge",
                            PersonImage = "",
                            PersonPosition = "Store Manager"
                        },
                        new
                        {
                            ID = 7,
                            Description = "Gosto muito de fazer parte de uma empresa que desenvolve os colaboradores tanto a nível profissional como pessoal. Todos os dias aprendo muito acerca dos outros e de mim própria. Há sempre atitude, há sempre paixão, e um entusiasmo contagiante!",
                            NamePerson = "Manuela",
                            PersonImage = "",
                            PersonPosition = "Store Manager"
                        },
                        new
                        {
                            ID = 8,
                            Description = "Trabalhar na Brodheim é ser parte de uma história com mais de 70 anos; é trabalhar com vontade, com garra de vencer e de superar! Comecei como vendedor, fui ultrapassando todos os desafios que me foram propostos, até me tornar Area Manager, função que desempenho hoje.",
                            NamePerson = "Pedro",
                            PersonImage = "",
                            PersonPosition = "Area Manager"
                        },
                        new
                        {
                            ID = 9,
                            Description = "Trabalhar na Brodheim é fazer parte de uma cultura forte, onde os seus valores são vividos diariamente. É fazer parte de um projeto de responsabilidade social sólido, no qual as equipas estão envolvidas. É estar no Top 20 das melhores empresas para trabalhar em Portugal. É querer sempre mais!",
                            NamePerson = "Sofia",
                            PersonImage = "",
                            PersonPosition = " People & Talent Development"
                        });
                });

            modelBuilder.Entity("Brodheim.Models.Oportunidades", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DateTrabalho")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetalhesFuncao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageEmpresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFuncao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeTrabalho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoContrato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Oportunidades", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateTrabalho = new DateTime(2023, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DetalhesFuncao = "Com mais de 75 anos de história e crescimento, o Grupo Brodheim é hoje a mais importante empresa de moda e ótica em Portugal. Com a visão de ser a referência na gestão de retalho premium no mundo da moda e da ótica, é considerada uma das Melhores Empresas Para Trabalhar em Portugal, e o lugar onde tu queres estar! A missão de proporcionar a todos os nossos clientes e stakeholders, um serviço de excelência e uma experiência comercial e relacional única, é sentida e vivida todos os dias pelos nossos colaboradores que incorporam os nossos valores: ambição, sustentabilidade, credibilidade, empowerment e atitude.\r\n\r\nVeste a camisola VANS, na nossa loja no MadeiraShopping, em regime Full-Time 40h (rotativo).\r\n\r\nA TUA MISSÃO:\r\n– Garantir uma experiência comercial de excelência\r\n– Garantir vendas\r\n– Assegurar as tarefas diárias da loja\r\n– Reportar diretamente ao Store Manager\r\n\r\nQUE PERFIL PROCURAMOS?\r\nO candidato ideal terá o seguinte perfil:\r\n– Experiência no retalho, em marcas do mesmo segmento (preferencial)\r\n– Gosto por proporcionar uma experiência comercial excecional\r\n– Ótimas competências comunicacionais\r\n– Elevado perfil comercial\r\n– Foco no cumprimento de objetivos\r\n– Conhecimentos de inglês em contexto de vendas\r\n– Disponibilidade para realizar horários rotativos e flexíveis\r\n– Carta de condução, viatura própria (requisito preferencial para deslocação para o shopping)\r\n\r\nO QUE TE OFERECEMOS:\r\n– Um ambiente de trabalho envolvente\r\n– Possibilidade de crescimento e progressão na carreira\r\n– Oportunidade de Formação especializada contínua\r\n– Incentivos mensais\r\n– Participação em ações de solidariedade social e ambiental\r\n– Protocolos e parcerias exclusivas para colaboradores do Grupo Brodheim\r\n\r\nSe reúnes os requisitos, esta vaga é para ti!",
                            ImageEmpresa = "",
                            Localizacao = "Funchal",
                            NomeEmpresa = "Vans",
                            NomeFuncao = "Sales Assistant",
                            NomeTrabalho = "Sales Assistant (M/F) – Vans Funchal | FT",
                            TipoContrato = "Full Time"
                        },
                        new
                        {
                            ID = 2,
                            DateTrabalho = new DateTime(2023, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DetalhesFuncao = "Com mais de 75 anos de história e crescimento, o Grupo Brodheim é hoje a mais importante empresa de moda e ótica em Portugal. Com a visão de ser a referência na gestão de retalho premium no mundo da moda e da ótica, é considerada uma das Melhores Empresas Para Trabalhar em Portugal, e o lugar onde tu queres estar! A missão de proporcionar a todos os nossos clientes e stakeholders, um serviço de excelência e uma experiência comercial e relacional única, é sentida e vivida todos os dias pelos nossos colaboradores que incorporam os nossos valores: ambição, sustentabilidade, credibilidade, empowerment e atitude.\r\n\r\nVeste a camisola VANS, na nossa loja no MadeiraShopping, em regime Full-Time 40h (rotativo).\r\n\r\nA TUA MISSÃO:\r\n– Garantir uma experiência comercial de excelência\r\n– Garantir vendas\r\n– Assegurar as tarefas diárias da loja\r\n– Reportar diretamente ao Store Manager\r\n\r\nQUE PERFIL PROCURAMOS?\r\nO candidato ideal terá o seguinte perfil:\r\n– Experiência no retalho, em marcas do mesmo segmento (preferencial)\r\n– Gosto por proporcionar uma experiência comercial excecional\r\n– Ótimas competências comunicacionais\r\n– Elevado perfil comercial\r\n– Foco no cumprimento de objetivos\r\n– Conhecimentos de inglês em contexto de vendas\r\n– Disponibilidade para realizar horários rotativos e flexíveis\r\n– Carta de condução, viatura própria (requisito preferencial para deslocação para o shopping)\r\n\r\nO QUE TE OFERECEMOS:\r\n– Um ambiente de trabalho envolvente\r\n– Possibilidade de crescimento e progressão na carreira\r\n– Oportunidade de Formação especializada contínua\r\n– Incentivos mensais\r\n– Participação em ações de solidariedade social e ambiental\r\n– Protocolos e parcerias exclusivas para colaboradores do Grupo Brodheim\r\n\r\nSe reúnes os requisitos, esta vaga é para ti!",
                            ImageEmpresa = "",
                            Localizacao = "Lisboa",
                            NomeEmpresa = "Timberland",
                            NomeFuncao = "Sales Assistant",
                            NomeTrabalho = "Sales Assistant (M/F) – Timberland Amoreiras | PT",
                            TipoContrato = "Part Time"
                        },
                        new
                        {
                            ID = 3,
                            DateTrabalho = new DateTime(2023, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DetalhesFuncao = "Com mais de 75 anos de história e crescimento, o Grupo Brodheim é hoje a mais importante empresa de moda e ótica em Portugal. Com a visão de ser a referência na gestão de retalho premium no mundo da moda e da ótica, é considerada uma das Melhores Empresas Para Trabalhar em Portugal, e o lugar onde tu queres estar! A missão de proporcionar a todos os nossos clientes e stakeholders, um serviço de excelência e uma experiência comercial e relacional única, é sentida e vivida todos os dias pelos nossos colaboradores que incorporam os nossos valores: ambição, sustentabilidade, credibilidade, empowerment e atitude.\r\n\r\nVeste a camisola VANS, na nossa loja no MadeiraShopping, em regime Full-Time 40h (rotativo).\r\n\r\nA TUA MISSÃO:\r\n– Garantir uma experiência comercial de excelência\r\n– Garantir vendas\r\n– Assegurar as tarefas diárias da loja\r\n– Reportar diretamente ao Store Manager\r\n\r\nQUE PERFIL PROCURAMOS?\r\nO candidato ideal terá o seguinte perfil:\r\n– Experiência no retalho, em marcas do mesmo segmento (preferencial)\r\n– Gosto por proporcionar uma experiência comercial excecional\r\n– Ótimas competências comunicacionais\r\n– Elevado perfil comercial\r\n– Foco no cumprimento de objetivos\r\n– Conhecimentos de inglês em contexto de vendas\r\n– Disponibilidade para realizar horários rotativos e flexíveis\r\n– Carta de condução, viatura própria (requisito preferencial para deslocação para o shopping)\r\n\r\nO QUE TE OFERECEMOS:\r\n– Um ambiente de trabalho envolvente\r\n– Possibilidade de crescimento e progressão na carreira\r\n– Oportunidade de Formação especializada contínua\r\n– Incentivos mensais\r\n– Participação em ações de solidariedade social e ambiental\r\n– Protocolos e parcerias exclusivas para colaboradores do Grupo Brodheim\r\n\r\nSe reúnes os requisitos, esta vaga é para ti!",
                            ImageEmpresa = "",
                            Localizacao = "Lisboa",
                            NomeEmpresa = "Emporio Armani",
                            NomeFuncao = "Sales Assistant",
                            NomeTrabalho = "Sales Assistant (M/F) – Emporio Armani (Full-Time)",
                            TipoContrato = "Full Time"
                        },
                        new
                        {
                            ID = 4,
                            DateTrabalho = new DateTime(2023, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DetalhesFuncao = "Com mais de 75 anos de história e crescimento, o Grupo Brodheim é hoje a mais importante empresa de moda e ótica em Portugal. Com a visão de ser a referência na gestão de retalho premium no mundo da moda e da ótica, é considerada uma das Melhores Empresas Para Trabalhar em Portugal, e o lugar onde tu queres estar! A missão de proporcionar a todos os nossos clientes e stakeholders, um serviço de excelência e uma experiência comercial e relacional única, é sentida e vivida todos os dias pelos nossos colaboradores que incorporam os nossos valores: ambição, sustentabilidade, credibilidade, empowerment e atitude.\r\n\r\nVeste a camisola VANS, na nossa loja no MadeiraShopping, em regime Full-Time 40h (rotativo).\r\n\r\nA TUA MISSÃO:\r\n– Garantir uma experiência comercial de excelência\r\n– Garantir vendas\r\n– Assegurar as tarefas diárias da loja\r\n– Reportar diretamente ao Store Manager\r\n\r\nQUE PERFIL PROCURAMOS?\r\nO candidato ideal terá o seguinte perfil:\r\n– Experiência no retalho, em marcas do mesmo segmento (preferencial)\r\n– Gosto por proporcionar uma experiência comercial excecional\r\n– Ótimas competências comunicacionais\r\n– Elevado perfil comercial\r\n– Foco no cumprimento de objetivos\r\n– Conhecimentos de inglês em contexto de vendas\r\n– Disponibilidade para realizar horários rotativos e flexíveis\r\n– Carta de condução, viatura própria (requisito preferencial para deslocação para o shopping)\r\n\r\nO QUE TE OFERECEMOS:\r\n– Um ambiente de trabalho envolvente\r\n– Possibilidade de crescimento e progressão na carreira\r\n– Oportunidade de Formação especializada contínua\r\n– Incentivos mensais\r\n– Participação em ações de solidariedade social e ambiental\r\n– Protocolos e parcerias exclusivas para colaboradores do Grupo Brodheim\r\n\r\nSe reúnes os requisitos, esta vaga é para ti!",
                            ImageEmpresa = "",
                            Localizacao = "Vila do Conde - Porto",
                            NomeEmpresa = "Timberland",
                            NomeFuncao = "Sales Assistant",
                            NomeTrabalho = "Sales Assistant (M/F) – Timberland Outlet Vila do Conde | FT",
                            TipoContrato = "Full Time"
                        },
                        new
                        {
                            ID = 5,
                            DateTrabalho = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DetalhesFuncao = "Com mais de 75 anos de história e crescimento, o Grupo Brodheim é hoje a mais importante empresa de moda e ótica em Portugal. Com a visão de ser a referência na gestão de retalho premium no mundo da moda e da ótica, é considerada uma das Melhores Empresas Para Trabalhar em Portugal, e o lugar onde tu queres estar! A missão de proporcionar a todos os nossos clientes e stakeholders, um serviço de excelência e uma experiência comercial e relacional única, é sentida e vivida todos os dias pelos nossos colaboradores que incorporam os nossos valores: ambição, sustentabilidade, credibilidade, empowerment e atitude.\r\n\r\nVeste a camisola VANS, na nossa loja no MadeiraShopping, em regime Full-Time 40h (rotativo).\r\n\r\nA TUA MISSÃO:\r\n– Garantir uma experiência comercial de excelência\r\n– Garantir vendas\r\n– Assegurar as tarefas diárias da loja\r\n– Reportar diretamente ao Store Manager\r\n\r\nQUE PERFIL PROCURAMOS?\r\nO candidato ideal terá o seguinte perfil:\r\n– Experiência no retalho, em marcas do mesmo segmento (preferencial)\r\n– Gosto por proporcionar uma experiência comercial excecional\r\n– Ótimas competências comunicacionais\r\n– Elevado perfil comercial\r\n– Foco no cumprimento de objetivos\r\n– Conhecimentos de inglês em contexto de vendas\r\n– Disponibilidade para realizar horários rotativos e flexíveis\r\n– Carta de condução, viatura própria (requisito preferencial para deslocação para o shopping)\r\n\r\nO QUE TE OFERECEMOS:\r\n– Um ambiente de trabalho envolvente\r\n– Possibilidade de crescimento e progressão na carreira\r\n– Oportunidade de Formação especializada contínua\r\n– Incentivos mensais\r\n– Participação em ações de solidariedade social e ambiental\r\n– Protocolos e parcerias exclusivas para colaboradores do Grupo Brodheim\r\n\r\nSe reúnes os requisitos, esta vaga é para ti!",
                            ImageEmpresa = "",
                            Localizacao = "Loulé - Faro",
                            NomeEmpresa = "Guess",
                            NomeFuncao = "Warehouse Assistant",
                            NomeTrabalho = "Warehouse Assistant (M/F) – Guess Outlet Loulé | FT",
                            TipoContrato = "Full Time"
                        },
                        new
                        {
                            ID = 6,
                            DateTrabalho = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DetalhesFuncao = "Com mais de 75 anos de história e crescimento, o Grupo Brodheim é hoje a mais importante empresa de moda e ótica em Portugal. Com a visão de ser a referência na gestão de retalho premium no mundo da moda e da ótica, é considerada uma das Melhores Empresas Para Trabalhar em Portugal, e o lugar onde tu queres estar! A missão de proporcionar a todos os nossos clientes e stakeholders, um serviço de excelência e uma experiência comercial e relacional única, é sentida e vivida todos os dias pelos nossos colaboradores que incorporam os nossos valores: ambição, sustentabilidade, credibilidade, empowerment e atitude.\r\n\r\nVeste a camisola VANS, na nossa loja no MadeiraShopping, em regime Full-Time 40h (rotativo).\r\n\r\nA TUA MISSÃO:\r\n– Garantir uma experiência comercial de excelência\r\n– Garantir vendas\r\n– Assegurar as tarefas diárias da loja\r\n– Reportar diretamente ao Store Manager\r\n\r\nQUE PERFIL PROCURAMOS?\r\nO candidato ideal terá o seguinte perfil:\r\n– Experiência no retalho, em marcas do mesmo segmento (preferencial)\r\n– Gosto por proporcionar uma experiência comercial excecional\r\n– Ótimas competências comunicacionais\r\n– Elevado perfil comercial\r\n– Foco no cumprimento de objetivos\r\n– Conhecimentos de inglês em contexto de vendas\r\n– Disponibilidade para realizar horários rotativos e flexíveis\r\n– Carta de condução, viatura própria (requisito preferencial para deslocação para o shopping)\r\n\r\nO QUE TE OFERECEMOS:\r\n– Um ambiente de trabalho envolvente\r\n– Possibilidade de crescimento e progressão na carreira\r\n– Oportunidade de Formação especializada contínua\r\n– Incentivos mensais\r\n– Participação em ações de solidariedade social e ambiental\r\n– Protocolos e parcerias exclusivas para colaboradores do Grupo Brodheim\r\n\r\nSe reúnes os requisitos, esta vaga é para ti!",
                            ImageEmpresa = "",
                            Localizacao = "Lisboa",
                            NomeEmpresa = "Michael Kors",
                            NomeFuncao = "Sales Assistant",
                            NomeTrabalho = "Sales Assistant (M/F) – Michael Kors Aeroporto de Lisboa | FT",
                            TipoContrato = "Full Time"
                        },
                        new
                        {
                            ID = 7,
                            DateTrabalho = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DetalhesFuncao = "Com mais de 75 anos de história e crescimento, o Grupo Brodheim é hoje a mais importante empresa de moda e ótica em Portugal. Com a visão de ser a referência na gestão de retalho premium no mundo da moda e da ótica, é considerada uma das Melhores Empresas Para Trabalhar em Portugal, e o lugar onde tu queres estar! A missão de proporcionar a todos os nossos clientes e stakeholders, um serviço de excelência e uma experiência comercial e relacional única, é sentida e vivida todos os dias pelos nossos colaboradores que incorporam os nossos valores: ambição, sustentabilidade, credibilidade, empowerment e atitude.\r\n\r\nVeste a camisola VANS, na nossa loja no MadeiraShopping, em regime Full-Time 40h (rotativo).\r\n\r\nA TUA MISSÃO:\r\n– Garantir uma experiência comercial de excelência\r\n– Garantir vendas\r\n– Assegurar as tarefas diárias da loja\r\n– Reportar diretamente ao Store Manager\r\n\r\nQUE PERFIL PROCURAMOS?\r\nO candidato ideal terá o seguinte perfil:\r\n– Experiência no retalho, em marcas do mesmo segmento (preferencial)\r\n– Gosto por proporcionar uma experiência comercial excecional\r\n– Ótimas competências comunicacionais\r\n– Elevado perfil comercial\r\n– Foco no cumprimento de objetivos\r\n– Conhecimentos de inglês em contexto de vendas\r\n– Disponibilidade para realizar horários rotativos e flexíveis\r\n– Carta de condução, viatura própria (requisito preferencial para deslocação para o shopping)\r\n\r\nO QUE TE OFERECEMOS:\r\n– Um ambiente de trabalho envolvente\r\n– Possibilidade de crescimento e progressão na carreira\r\n– Oportunidade de Formação especializada contínua\r\n– Incentivos mensais\r\n– Participação em ações de solidariedade social e ambiental\r\n– Protocolos e parcerias exclusivas para colaboradores do Grupo Brodheim\r\n\r\nSe reúnes os requisitos, esta vaga é para ti!",
                            ImageEmpresa = "",
                            Localizacao = "Lisboa",
                            NomeEmpresa = "Brodheim",
                            NomeFuncao = "Trade Marketing",
                            NomeTrabalho = "Trade Marketing (M/F) – Substituição de Licença de Maternidade",
                            TipoContrato = "Full Time"
                        });
                });

            modelBuilder.Entity("Brodheim.Models.Passos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DescricaoPasso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePasso")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Passos", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DescricaoPasso = "Pode candidatar-se online à posição que lhe interessa através da opção “Candidatura”. Terá a oportunidade de partilhar as suas competências, formação e experiência profissional connosco.",
                            ImagePasso = ""
                        },
                        new
                        {
                            ID = 2,
                            DescricaoPasso = "Cada candidatura é cuidadosamente analisada pelos nossos especialistas de recrutamento. A nossa pré-seleção foca-se na combinação de elementos relativos à sua formação, percurso e experiência profissional. Esta fase permite-nos avaliar os dados curriculares e analisar se se enquadram com a missão da função para a qual estamos a recrutar.",
                            ImagePasso = ""
                        },
                        new
                        {
                            ID = 3,
                            DescricaoPasso = "Se a sua candidatura for bem sucedida, neste fase irá conhecer os vários intervenientes da função a que se está a candidatar. Neste processo pode saber mais sobre o Grupo e sobre o projeto em causa. A nós permite-nos conhecer as suas motivações e analisar as suas competências técnicas e comportamentais. Esta etapa pode incluir várias e diferentes interações sobre a forma de entrevistas, exercícios práticos ou dinâmicas de grupo, dependendo da função em causa.",
                            ImagePasso = ""
                        },
                        new
                        {
                            ID = 4,
                            DescricaoPasso = "Os vários intervenientes neste processo reúnem-se e tomam uma decisão.",
                            ImagePasso = ""
                        },
                        new
                        {
                            ID = 5,
                            DescricaoPasso = "Se a sua candidatura for bem sucedida em todas as fases anteriores, irá receber um contacto nosso com uma oferta de emprego. Em caso de ficar excluído deste processo receberá também uma notificação por email.",
                            ImagePasso = ""
                        },
                        new
                        {
                            ID = 6,
                            DescricaoPasso = "O seu processo de integração inicia-se na data da sua admissão e tem uma duração entre 30 a 90 dias, dependendo da função. Nessa altura é traçado um plano personalizado de integração e formação que será o ponto de partida de um caminho que lhe permita maximizar o seu potencial dentro do nosso Grupo.",
                            ImagePasso = ""
                        });
                });

            modelBuilder.Entity("Brodheim.Models.QuemSomos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ImageRepresentative")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameRepresentative")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityRepresentative")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("QuemSomos", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ImageRepresentative = "",
                            NameRepresentative = "Colaboradores",
                            QuantityRepresentative = 600
                        },
                        new
                        {
                            ID = 2,
                            ImageRepresentative = "",
                            NameRepresentative = "Lojas",
                            QuantityRepresentative = 70
                        },
                        new
                        {
                            ID = 3,
                            ImageRepresentative = "",
                            NameRepresentative = "Marcas",
                            QuantityRepresentative = 12
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
